swagger: "2.0"
info:
  title: Music10 API
  description: API for Music10 server.
  version: 1.0.0
host: api.music.dergunov.net
schemes:
  - https
paths:
  /playlists:
    get:
      summary: Get playlists
      description: Returns a list of playlists.
      produces:
        - application/json
      parameters:
        - name: "query"
          in: "query"
          description: "Query string for search playlists by name"
          required: false
          type: "string"
      responses:
        200:
          description: OK
          schema:
            type: "array"
            items:
              $ref: "#/definitions/Playlist"

            example:
              - id: 1
                name: Русский рэп
              - id: 2
                name: Дискотека 80х
  /playlists/{id}:
    get:
      summary: "Get playlist by ID"
      description: "Returns a single playlist"
      produces:
        - application/json
      parameters:
        - name: "id"
          in: "path"
          description: "ID of playlist to return"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: OK
          schema:
            $ref: "#/definitions/Playlist"
definitions:
  Playlist:
    type: "object"
    properties:
      id:
        type: integer
      name:
        type: string
    example:
      id: 1
      name: Русский рэп